### ISSUE TITLE
Key name for redis

### ISSUE THREAD

**Issue by manjeetlakra** [Shakeeljaveed/zabbix-redis-userparamaters#1]
Can you please tell what are the keys name needs to be configure at zabbix UI ?

**Comment by Shakeeljaveed** [comment]
@manjeetlakra  Please find this user parameter in this **total_connections_received** is the key name needs to be configured in Zabbix UI 

UserParameter=**total_connections_received**,grep -w 'total_connections_received' /tmp/redismetric | cut -d: -f2
